#
# This file contains configuration flags to customize your site
#

name: "Keyin's Blog"
description: "Tech Art | Computer Graphics | Programming Self-Study"

#
# Flags below are optional
#

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://github.com/keyinwu/blog/raw/main/images/avatar.jpg
# 64px × 64px recommended
favicon: https://raw.githubusercontent.com/keyinwu/blog/main/images/favicon.ico

navigation:
  - name: Blog
    url: /
  - name: About
    url: https://www.keyinw.site/#about_me
  - name: Archive
    url: /archive
  - name: Tags
    url: /tags

# Pagination
paginate: 8

excerpt_separator: <!-- more -->

# Includes an icon in the footer for each username you enter
footer-links:
  #weibo: frommidworld  https://www.weibo.com/<thispart>
  behance: # https://www.behance.net/<username>
  dribbble:
  zhihu: 
  email: quoeyee@gmail.com
  facebook:
  flickr:
  github: keyinwu
  googleplus: # anything in your profile username that comes after plus.google.com/
  instagram: quoey_gallery
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  tumblr: # https://<username>.tumblr.com
  #twitter: frommidworld
  youtube:

# Text under the icons in footer
footer-text: Copyright © 2022 Keyin Wu

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: # fromendworld

# Gitalk
gitalk:
  clientID: 4eb3ad2e5798e27b38f7
  clientSecret: b3b0c93cc48b16f0b1575e44a1525049208a115e
  repo: blog
  owner: keyinwu

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
#google_analytics: 

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://keyinwu.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: /blog

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME


theme: jekyll-theme-minimal